version: '3'

services:
  php:
    container_name: yii-php
    image: yiisoftware/yii-php:8.1-fpm
    working_dir: /app
    volumes:
      - ./:/app
  nginx:
    image: nginx:alpine
    container_name: yii-nginx
    ports:
      - 8080:80
      - 8081:81
    volumes:
      - ./:/app
      - ./data/nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
    restart: always

  worker:
    image: yiisoftware/yii-php:8.1-fpm
    working_dir: /app
    command: bash -c "/app/yii queue/listen channel-1 -vvv"
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.9.20-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "app"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "app"
